import type { Command, Option } from 'commander';

export type CompletionShell = 'bash' | 'zsh' | 'fish';

/**
 * Static shell-completion generator: walks the Commander tree once at
 * `aria completion <shell>` time and emits a self-contained script.
 * Hidden commands (machine-facing protocols, deprecated aliases) are
 * skipped so completion mirrors `aria --help`.
 */

interface CompletionNode {
  name: string;
  path: string[]; // subcommand path from the root, e.g. ['trigger', 'grant']
  description: string;
  options: { long?: string; short?: string; description: string }[];
  children: CompletionNode[];
}

function isHidden(cmd: Command): boolean {
  // Commander exposes hidden-ness only through the private `_hidden` field.
  return Boolean((cmd as unknown as { _hidden?: boolean })._hidden);
}

function optionWords(opt: Option): { long?: string; short?: string; description: string } {
  return { long: opt.long, short: opt.short, description: opt.description ?? '' };
}

function buildTree(root: Command): CompletionNode {
  const walk = (cmd: Command, path: string[]): CompletionNode => ({
    name: cmd.name(),
    path,
    description: cmd.description(),
    options: cmd.options.filter((o) => !o.hidden).map(optionWords),
    children: cmd.commands.filter((c) => !isHidden(c)).map((c) => walk(c, [...path, c.name()])),
  });
  return walk(root, []);
}

/** words offered when the cursor sits inside `node`: child names + flags */
function nodeWords(node: CompletionNode): string[] {
  return [
    ...node.children.map((c) => c.name),
    ...node.options.flatMap((o) => [o.short, o.long].filter((w): w is string => Boolean(w))),
  ];
}

function flatNodes(root: CompletionNode): CompletionNode[] {
  return [root, ...root.children.flatMap(flatNodes)];
}

// ---------- bash ----------

function emitBash(root: CompletionNode): string {
  const entries = flatNodes(root)
    .map((n) => `  [${quoteBash(n.path.join(' '))}]=${quoteBash(nodeWords(n).join(' '))}`)
    .join('\n');
  return `# bash completion for ${root.name} — generated by \`aria completion bash\`
declare -A _aria_words=(
${entries}
)

_aria() {
  local cur path key w i
  cur="\${COMP_WORDS[COMP_CWORD]}"
  path=""
  for (( i=1; i<COMP_CWORD; i++ )); do
    w="\${COMP_WORDS[i]}"
    [[ "$w" == -* ]] && continue
    key="\${path:+$path }$w"
    if [[ -n "\${_aria_words[$key]+set}" ]]; then
      path="$key"
    fi
  done
  COMPREPLY=( $(compgen -W "\${_aria_words[$path]}" -- "$cur") )
  return 0
}

complete -F _aria ${root.name}
`;
}

function quoteBash(s: string): string {
  return `"${s.replace(/["\\$`]/g, '\\$&')}"`;
}

// ---------- zsh ----------

function emitZsh(root: CompletionNode): string {
  const entries = flatNodes(root)
    .map((n) => `    ${quoteZsh(n.path.join(' '))} ${quoteZsh(nodeWords(n).join(' '))}`)
    .join('\n');
  return `#compdef ${root.name}
# zsh completion for ${root.name} — generated by \`aria completion zsh\`
_${root.name.replace(/-/g, '_')}() {
  local -A _aria_words
  _aria_words=(
${entries}
  )
  local path="" key w i
  for (( i=2; i<CURRENT; i++ )); do
    w="$words[i]"
    [[ "$w" == -* ]] && continue
    key="\${path:+$path }$w"
    if [[ -n "\${_aria_words[$key]}" ]]; then
      path="$key"
    fi
  done
  local -a candidates
  candidates=( \${(z)_aria_words[$path]} )
  compadd -- $candidates
}

_${root.name.replace(/-/g, '_')} "$@"
`;
}

function quoteZsh(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

// ---------- fish ----------

function emitFish(root: CompletionNode): string {
  const lines: string[] = [
    `# fish completion for ${root.name} — generated by \`aria completion fish\``,
    `complete -c ${root.name} -f`,
  ];
  const visit = (node: CompletionNode): void => {
    const parentCond = node.path.length === 0
      ? '__fish_use_subcommand'
      : `__fish_seen_subcommand_from ${node.path[node.path.length - 1]}`;
    // Offer each child once — suppress after any sibling was picked.
    const siblings = node.children.map((c) => c.name).join(' ');
    for (const child of node.children) {
      const cond = node.path.length === 0
        ? '__fish_use_subcommand'
        : `${parentCond}; and not __fish_seen_subcommand_from ${siblings}`;
      lines.push(
        `complete -c ${root.name} -n '${cond}' -a ${quoteFish(child.name)} -d ${quoteFish(child.description)}`,
      );
      for (const opt of child.options) {
        const parts = [`complete -c ${root.name}`, `-n '__fish_seen_subcommand_from ${child.name}'`];
        if (opt.short) parts.push(`-s ${opt.short.replace(/^-/, '')}`);
        if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, '')}`);
        parts.push(`-d ${quoteFish(opt.description)}`);
        lines.push(parts.join(' '));
      }
      visit(child);
    }
    // Options on the root command itself.
    if (node.path.length === 0) {
      for (const opt of node.options) {
        const parts = [`complete -c ${root.name}`];
        if (opt.short) parts.push(`-s ${opt.short.replace(/^-/, '')}`);
        if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, '')}`);
        parts.push(`-d ${quoteFish(opt.description)}`);
        lines.push(parts.join(' '));
      }
    }
  };
  visit(root);
  return `${lines.join('\n')}\n`;
}

function quoteFish(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function emitCompletion(program: Command, shell: CompletionShell): string {
  const root = buildTree(program);
  switch (shell) {
    case 'bash':
      return emitBash(root);
    case 'zsh':
      return emitZsh(root);
    case 'fish':
      return emitFish(root);
  }
}
